version: "2.24"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
  sink:
    build:
      context: ./sink
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    depends_on:
      - redis 
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  # redis-stack:
  #   image: redis/redis-stack
  #   ports:
  #     - "8001:8001"

volumes:
  mongo_data:
  redis_data:
    